FROM golang:1.21-alpine

  # Install git
RUN set -ex; \
apk update; \
apk add --no-cache git

  # Set working directory
  # TODO replace template-serverless-service
WORKDIR /go/src/github.com/pennsieve/template-serverless-service/lambda/service

  # Run tests
CMD CGO_ENABLED=0 go test -v ./...
